name: Daily News Automation

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  test-simple:
    runs-on: ubuntu-latest
    steps:
    - name: Simple API Test
      env:
        COZE_TOKEN: ${{ secrets.COZE_TOKEN }}
      run: |
        echo "=== 基础API测试 ==="
        echo "工作流ID: 7562209382487113774"
        echo "Token长度: ${#COZE_TOKEN}"
        
        # 最简单的curl命令
        curl -X POST "https://api.coze.cn/v1/workflow/stream_run" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $COZE_TOKEN" \
          -d '{
            "workflow_id": "7562209382487113774",
            "parameters": {
              "input": "https://auto.163.com/"
            }
          }' \
          -w "\n状态码: %{http_code}\n" \
          -s
